## Set Up ##

In [1]:
#download staffing, exec pivot, the 3 TBM ESC files (https://app.powerbigov.us/groups/711b4b6c-92eb-4c57-badc-11b293e42bf1/list)
#, last month's folder, cloud file (if possible)

In [2]:
import os
import shutil
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import time
import openpyxl
from openpyxl import load_workbook
from openpyxl.worksheet.table import Table, TableStyleInfo
import pandas as pd
import xlwings as xw
import numpy as np
start_master = time.time()

In [3]:
download_path = input("Enter path to folder where all raw sources files are downloaded: ")
#C:\Users\stephalin\Downloads
src_folder = os.path.join(download_path, input("Enter source folder name: "))

raw_Staff = os.path.join(download_path, input("Enter Staffing source file name: ") + ".xlsx")
raw_EP = os.path.join(download_path, input("Enter Execution Pivot source file name: ") + ".xlsx")
raw_Cloud = os.path.join(download_path, input("Enter ESC Cloud source file name: ") + "." + input("xlsx or csv?"))
raw_CostPool = os.path.join(download_path,"TBM ESC Cost Pool.xlsx")
raw_Sol = os.path.join(download_path,"TBM ESC Solutions.xlsx")
raw_T = os.path.join(download_path,"TBM ESC Tower.xlsx")

Enter path to folder where all raw sources files are downloaded:  C:\Users\stephalin\Downloads
Enter source folder name:  FY25 August
Enter Staffing source file name:  RMS Staffing Projections & Actuals_FY25FINAL
Enter Execution Pivot source file name:  RMS Execution Pivot Report_FY25FINAL
Enter ESC Cloud source file name:  ESCID Report Oct24-Sept25
xlsx or csv? xlsx

### Copying and renaming source folder ###

In [4]:
today = datetime.today()

#to test on last month's data, uncomment
#today = today - relativedelta(months=1)

print("Today is:", today)
first_of_month = today.replace(day=1)
prior_month_date = first_of_month - timedelta(days=1)
print("We will create data inputs for", prior_month_date.strftime("%B"), prior_month_date.year, "dashboard")

Today is: 2025-11-19 11:15:53.972847
We will create data inputs for October 2025 dashboard

In [5]:
#src_folder = r'C:\Users\stephalin\Downloads\FY25 June - Q3'
#dst_folder = r'C:\Users\stephalin\Downloads\FY25 July'
first_of_month = today.replace(day=1)
prior_month_date = first_of_month - timedelta(days=1)
year_str = str(prior_month_date.year)[-2:]
month_str = prior_month_date.strftime("%B")
quarter_map = {3: "Q1", 6: "Q2", 9: "Q3", 12: "Q4"}
quarter_suffix = ""
if prior_month_date.month in quarter_map:
    quarter_suffix = f" - {quarter_map[prior_month_date.month]}"

parent_folder = os.path.dirname(src_folder)
dst_folder_name = f"FY{year_str} {month_str}{quarter_suffix}"
dst_folder = os.path.join(parent_folder, dst_folder_name)

date_str = datetime.now().strftime('%Y%m%d')

os.makedirs(dst_folder, exist_ok=True)
for root, dirs, files in os.walk(src_folder):
    for filename in files:
        ext = os.path.splitext(filename)[1].lower()
        src_path = os.path.join(root, filename)
        if ext == ".xlsm":
            new_name = f"Model Enhancements_{date_str}{ext}"
        elif "Golden PowerBI Source File" in filename and ext == ".xlsx":
            new_name = f"Golden PowerBI Source File_{date_str}{ext}"
        elif ext == ".pbix":
            new_name = f"FY2025 OCIO TBM Analytics{ext}"
        else:
            continue
        shutil.copy2(src_path, os.path.join(dst_folder, new_name))

print("Copying contents of " + src_folder + " into " + dst_folder)
raw_data_src = os.path.join(src_folder, "Raw Data")
raw_data_dst = os.path.join(dst_folder, "Raw Data")
if os.path.exists(raw_data_src):
    shutil.copytree(raw_data_src, raw_data_dst, dirs_exist_ok=True)

for filename in os.listdir(raw_data_dst):
    file_path = os.path.join(raw_data_dst, filename)
    if os.path.isfile(file_path):
        base, ext = os.path.splitext(filename)
        base = base.split("_")[0]
        new_name = f"{base}_{date_str}{ext}"
        new_path = os.path.join(raw_data_dst, new_name)
        os.rename(file_path, new_path)
print("All contents have been copied and renamed in "+ dst_folder)

Copying contents of C:\Users\stephalin\Downloads\FY25 August into C:\Users\stephalin\Downloads\FY25 October
All contents have been copied and renamed in C:\Users\stephalin\Downloads\FY25 October

## Refreshing data inputs ##

### Execution Pivot ###

In [6]:
start1 = time.time()
dst_EP = raw_data_dst+"\RMS Execution Pivot Report_"+date_str+".xlsx"
print("Copying contents of "+raw_EP+" into "+dst_EP)
print(" ")

Copying contents of C:\Users\stephalin\Downloads\RMS Execution Pivot Report_FY25FINAL.xlsx into C:\Users\stephalin\Downloads\FY25 October\Raw Data\RMS Execution Pivot Report_20251119.xlsx

<>:2: SyntaxWarning: invalid escape sequence '\R'
<>:2: SyntaxWarning: invalid escape sequence '\R'
C:\Users\stephalin\AppData\Local\Temp\ipykernel_29748\1570110182.py:2: SyntaxWarning: invalid escape sequence '\R'
  dst_EP = raw_data_dst+"\RMS Execution Pivot Report_"+date_str+".xlsx"

In [7]:
# Read raw data
raw_df = pd.read_excel(raw_EP, sheet_name="Sheet1")

# Cleaned data
df = raw_df.rename(columns={
    "UFMS Vendor Recipient": "Vendor Recipient",
    "Vendor Name": "Vendor POC Name",
    "Vendor Email": "Vendor POC Email"
})
delete_cols = [
    "Projection Note",
    "Line Item Mechanism Target Award Date",
    "RAL",
    "Late Waiver Number",
    "Late Waiver Deadline",
    "Unreconciled Commitments",
    "Unreconciled Obligations"
]
df = df.drop(columns=delete_cols, errors="ignore")

with xw.App(visible=False) as app:
    wb = app.books.open(dst_EP)
    # Write cleaned data to "Sheet1"
    try:
        wb.sheets["Sheet1"].delete()
    except Exception:
        pass
    clean_sht = wb.sheets.add("Sheet1", before=wb.sheets[0])
    clean_sht.range("A1").options(index=False).value = df

    nrows, ncols = df.shape
    # +1 for header row
    table_range = clean_sht.range((1, 1), (nrows + 1, ncols)).api
    clean_table = clean_sht.api.ListObjects.Add(1, table_range, None, 1)
    clean_table.Name = "Table13"
    clean_table.TableStyle = "TableStyleMedium2"

    wb.save()
    wb.close()

EP_len = len(df)

In [8]:
end1 = time.time()
print(f"Elapsed time: {end1 - start1} seconds for EP")

Elapsed time: 39.52707839012146 seconds for EP

### Staffing Report ###

In [9]:
start2 = time.time()
dst_Staff = raw_data_dst+"\RMS Staffing Projections & Actuals_"+date_str+".xlsx"
print("Copying contents of "+raw_Staff+" into "+dst_Staff)

Copying contents of C:\Users\stephalin\Downloads\RMS Staffing Projections & Actuals_FY25FINAL.xlsx into C:\Users\stephalin\Downloads\FY25 October\Raw Data\RMS Staffing Projections & Actuals_20251119.xlsx

<>:2: SyntaxWarning: invalid escape sequence '\R'
<>:2: SyntaxWarning: invalid escape sequence '\R'
C:\Users\stephalin\AppData\Local\Temp\ipykernel_29748\4235163783.py:2: SyntaxWarning: invalid escape sequence '\R'
  dst_Staff = raw_data_dst+"\RMS Staffing Projections & Actuals_"+date_str+".xlsx"

In [10]:
#Staffing report

df = pd.read_excel(raw_Staff, sheet_name="Sheet1")
wcf_map = pd.read_excel(dst_Staff, sheet_name="WCF Mapping")
ocio_map = pd.read_excel(dst_Staff, sheet_name="OCIO Admin Codes")
Staff_len = len(df)

# Remove 'AFPS' from column headers
df.columns = [col.replace("AFPS", "").strip() for col in df.columns]

# Insert Full Name column
def full_name_formula(row):
    if pd.notnull(row.iloc[0]) and "Budget Staff Adjustment" in str(row.iloc[0]):
        return ""
    if (str(row.get("Last Name", "")) + str(row.get("First Name", ""))).strip() == "":
        return "Vacant"
    return f"{row.get('Last Name','')}, {row.get('First Name','')}".strip(", ")
record_id_idx = df.columns.get_loc("Record ID")
df.insert(record_id_idx, "Full Name", df.apply(full_name_formula, axis=1))

# Find the index after "Total Amount"
total_amt_idx = df.columns.get_loc("Total Amount") + 1

# Insert in reverse order
df.insert(total_amt_idx, "OCIO Assigned Office", "")
df.insert(total_amt_idx, "OCIO Funding Office", "")
df.insert(total_amt_idx, "Service Line", "")

In [11]:
df['Service Line'] = df['Payroll Dist. WCF Indicator'].map(
    wcf_map.set_index('WCFID')['FY21-22 Service Line Descriptions']
)
#df

In [12]:
df['EAC'] = np.where(
    df['Employee Admin Code'].str.strip() == '',
    '',
    'H' + df['Employee Admin Code'].str.split(' ').str[0]
)
#df[['Employee Admin Code','EAC']]
#look at Payroll Dist. CAN Admin Code if Employee Admin Code is not showing a match. 
#EAC is where in the system that employee is assigned to. Payroll is when u get paid via diff dept

In [13]:
df['OCIO Funding Office']= df['EAC'].map(ocio_map.set_index('Admin Code')['Office Abrv']).fillna('')
df['OCIO Assigned Office']= df['EAC'].map(ocio_map.set_index('Admin Code')['Office Abrv']).fillna('')

In [14]:
with xw.App(visible=False) as app:
    app.display_alerts = False
    app.screen_updating = False
    wb = app.books.open(dst_Staff)
    try:
        wb.sheets["Import Data"].delete()
    except Exception:
        pass
    sht = wb.sheets.add("Import Data", before=wb.sheets[0])
    sht.range("A1").options(index=False).value = df

    nrows, ncols = df.shape
    table_range = sht.range((1, 1), (nrows + 1, ncols)).api
    table = sht.api.ListObjects.Add(1, table_range, None, 1)
    table.Name = "Table13"

    wb.save()
    wb.close()

In [15]:
Staff_len = len(df)

In [16]:
end2 = time.time()
print(f"Elapsed time: {end2 - start2} seconds for Staffing")

Elapsed time: 20.909607410430908 seconds for Staffing

### TBM ESC ###

In [17]:
start3 = time.time()
dst_CostPool = raw_data_dst+"\TBM ESC Cost Pool_"+date_str+".xlsx"
print("Copying contents of "+raw_CostPool+" into "+dst_CostPool)

Copying contents of C:\Users\stephalin\Downloads\TBM ESC Cost Pool.xlsx into C:\Users\stephalin\Downloads\FY25 October\Raw Data\TBM ESC Cost Pool_20251119.xlsx

<>:2: SyntaxWarning: invalid escape sequence '\T'
<>:2: SyntaxWarning: invalid escape sequence '\T'
C:\Users\stephalin\AppData\Local\Temp\ipykernel_29748\2298528951.py:2: SyntaxWarning: invalid escape sequence '\T'
  dst_CostPool = raw_data_dst+"\TBM ESC Cost Pool_"+date_str+".xlsx"

In [18]:
cp_df = pd.read_excel(raw_CostPool, sheet_name="TBM ESC Cost Pool", header=1)
#df = df.iloc[1:].reset_index(drop=True)
CostPoolRaw_len = len(cp_df)

# Find the index after "Total Amount"
total_amt_idx = cp_df.columns.get_loc("CP Amount") + 1

# Insert in reverse order
cp_df.insert(total_amt_idx, "Service Line", "")
cp_df.insert(total_amt_idx, "Office", "")
cp_df.insert(total_amt_idx, "In OCIO?", "")

with pd.ExcelWriter(dst_CostPool, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    cp_df.to_excel(writer, sheet_name="TBM ESC Cost Pool", index=False)

wb = openpyxl.load_workbook(dst_CostPool)
ws = wb["TBM ESC Cost Pool"]

In [19]:
header = [cell.value for cell in ws[1]]
admin_code_col = header.index("Admin Code") + 1
investment_id_col = header.index("Investment ID") + 1
in_ocio_col = header.index("In OCIO?") + 1
office_col = header.index("Office") + 1
service_line_col = header.index("Service Line") + 1

for row in range(2, ws.max_row + 1):
    p_cell = f"{openpyxl.utils.get_column_letter(admin_code_col)}{row}"
    j_cell = f"{openpyxl.utils.get_column_letter(investment_id_col)}{row}"
    ws.cell(row=row, column=in_ocio_col).value = f'=ISNUMBER(SEARCH("HCAJR",{p_cell}))'
    ws.cell(row=row, column=office_col).value = (f'=IF(ISNA(VLOOKUP({p_cell},\'OCIO ADMIN CODES\'!A:I,9,FALSE)),"",VLOOKUP({p_cell},\'OCIO ADMIN CODES\'!A:I,9,FALSE))')    
    ws.cell(row=row, column=service_line_col).value = (f'=IF(ISNA(VLOOKUP({j_cell},\'FY25 Service Lines\'!A:C,3,FALSE)),"Other - Non OCIO",VLOOKUP({j_cell},\'FY25 Service Lines\'!A:C,3,FALSE))')   

wb.save(dst_CostPool)

In [20]:
dst_Sol = raw_data_dst+"\TBM ESC Solutions_"+date_str+".xlsx"
print("Copying contents of "+raw_Sol+" into "+dst_Sol)

df = pd.read_excel(raw_Sol, sheet_name="TBM ESC Solutions", header=1)
#df = df.iloc[1:].reset_index(drop=True)
SolRaw_len = len(df)


# Find the index after "Total Amount"
total_amt_idx = df.columns.get_loc("Amount") + 1

# Insert in reverse order
df.insert(total_amt_idx, "Service Line", "")
df.insert(total_amt_idx, "Office", "")
df.insert(total_amt_idx, "In OCIO?", "")

with pd.ExcelWriter(dst_Sol, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    df.to_excel(writer, sheet_name="TBM ESC Solutions", index=False)

wb = openpyxl.load_workbook(dst_Sol)
ws = wb["TBM ESC Solutions"]


header = [cell.value for cell in ws[1]]
admin_code_col = header.index("Admin Code") + 1
investment_id_col = header.index("Investment ID") + 1
in_ocio_col = header.index("In OCIO?") + 1
office_col = header.index("Office") + 1
service_line_col = header.index("Service Line") + 1

for row in range(2, ws.max_row + 1):
    p_cell = f"{openpyxl.utils.get_column_letter(admin_code_col)}{row}"
    j_cell = f"{openpyxl.utils.get_column_letter(investment_id_col)}{row}"
    ws.cell(row=row, column=in_ocio_col).value = f'=ISNUMBER(SEARCH("HCAJR",{p_cell}))'
    ws.cell(row=row, column=office_col).value = (f'=IF(ISNA(VLOOKUP({p_cell},\'OCIO ADMIN CODES\'!A:I,9,FALSE)),"",VLOOKUP({p_cell},\'OCIO ADMIN CODES\'!A:I,9,FALSE))')    
    ws.cell(row=row, column=service_line_col).value = (f'=IF(ISNA(VLOOKUP({j_cell},\'FY25 Service Lines\'!A:C,3,FALSE)),"Other - Non OCIO",VLOOKUP({j_cell},\'FY25 Service Lines\'!A:C,3,FALSE))')   

wb.save(dst_Sol)

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\stephalin\AppData\Local\Temp\ipykernel_29748\688287672.py:1: SyntaxWarning: invalid escape sequence '\T'
  dst_Sol = raw_data_dst+"\TBM ESC Solutions_"+date_str+".xlsx"

Copying contents of C:\Users\stephalin\Downloads\TBM ESC Solutions.xlsx into C:\Users\stephalin\Downloads\FY25 October\Raw Data\TBM ESC Solutions_20251119.xlsx

In [21]:
dst_T = raw_data_dst+"\TBM ESC Tower_"+date_str+".xlsx"
print("Copying contents of "+raw_T+" into "+dst_T)

df = pd.read_excel(raw_T, sheet_name="TBM ESC Tower", header=1)
OCIO_Admin = pd.read_excel(dst_T, sheet_name="OCIO ADMIN CODES", header=0)

#df = df.iloc[1:].reset_index(drop=True)
TowerRaw_len = len(df)

# Find the index after "Total Amount"
total_amt_idx = df.columns.get_loc("Amount") + 0

# Insert in reverse order
df.insert(total_amt_idx, "Service Line", "")
df.insert(total_amt_idx, "Office", "")
df.insert(total_amt_idx, "In OCIO?", "")
df['In OCIO?'] = df['Admin Code'].str.contains('HCAJR', na=False)
#OCIO_Admin

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\stephalin\AppData\Local\Temp\ipykernel_29748\1437040655.py:1: SyntaxWarning: invalid escape sequence '\T'
  dst_T = raw_data_dst+"\TBM ESC Tower_"+date_str+".xlsx"

Copying contents of C:\Users\stephalin\Downloads\TBM ESC Tower.xlsx into C:\Users\stephalin\Downloads\FY25 October\Raw Data\TBM ESC Tower_20251119.xlsx

In [22]:
df = df.drop(columns=['Office'])
df = df.merge(
    OCIO_Admin[['Admin Code', 'Office Abrv']],
    on='Admin Code',
    how='left'
).rename(columns={'Office Abrv': 'Office'})
#df

df_T = df

df_T[df_T['In OCIO?'] == True]

,Fiscal Year,ESC ID,System Support,System Name,Hosting Location,Surveillance System,Investment Name,Roll-Up?,Rollup ESC ID,Investment ID,...,Status,Division,Division.1,Org Common Name,Admin Code,Towers,In OCIO?,Service Line,Amount,Office
11,2025,6,Business Support,Administrative Codes,On-Premise - CDC Data Center,No,CDC OCIO Application,No,3160,3160,...,Active,Digital Services Office,Digital Services Office,OCIO,HCAJRJB,Data Center,True,,0,DSO
12,2025,6,Business Support,Administrative Codes,On-Premise - CDC Data Center,No,CDC OCIO Application,No,3160,3160,...,Active,Digital Services Office,Digital Services Office,OCIO,HCAJRJB,Network,True,,0,DSO
13,2025,6,Business Support,Administrative Codes,On-Premise - CDC Data Center,No,CDC OCIO Application,No,3160,3160,...,Active,Digital Services Office,Digital Services Office,OCIO,HCAJRJB,Compute,True,,0,DSO
14,2025,6,Business Support,Administrative Codes,On-Premise - CDC Data Center,No,CDC OCIO Application,No,3160,3160,...,Active,Digital Services Office,Digital Services Office,OCIO,HCAJRJB,Storage,True,,0,DSO
15,2025,6,Business Support,Administrative Codes,On-Premise - CDC Data Center,No,CDC OCIO Application,No,3160,3160,...,Active,Digital Services Office,Digital Services Office,OCIO,HCAJRJB,Platform,True,,0,DSO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25834,2027,3497,NaN,CSPO Enterprise Log Collection,"Public Cloud - Microsoft Azure, Amazon Web Ser...",NaN,CDC OCIO Security and Compliance,No,0,3150,...,Active,Cybersecurity Program Office,Cybersecurity Program Office,OCIO,HCAJRKE,End User,True,,0,CSPO
25835,2027,3497,NaN,CSPO Enterprise Log Collection,"Public Cloud - Microsoft Azure, Amazon Web Ser...",NaN,CDC OCIO Security and Compliance,No,0,3150,...,Active,Cybersecurity Program Office,Cybersecurity Program Office,OCIO,HCAJRKE,Application,True,,0,CSPO
25836,2027,3497,NaN,CSPO Enterprise Log Collection,"Public Cloud - Microsoft Azure, Amazon Web Ser...",NaN,CDC OCIO Security and Compliance,No,0,3150,...,Active,Cybersecurity Program Office,Cybersecurity Program Office,OCIO,HCAJRKE,Delivery,True,,0,CSPO
25837,2027,3497,NaN,CSPO Enterprise Log Collection,"Public Cloud - Microsoft Azure, Amazon Web Ser...",NaN,CDC OCIO Security and Compliance,No,0,3150,...,Active,Cybersecurity Program Office,Cybersecurity Program Office,OCIO,HCAJRKE,Security & Compliance,True,,0,CSPO
25838,2027,3497,NaN,CSPO Enterprise Log Collection,"Public Cloud - Microsoft Azure, Amazon Web Ser...",NaN,CDC OCIO Security and Compliance,No,0,3150,...,Active,Cybersecurity Program Office,Cybersecurity Program Office,OCIO,HCAJRKE,IT Management,True,,0,CSPO

In [23]:
with pd.ExcelWriter(dst_T, engine="openpyxl", mode="a", if_sheet_exists="replace") as writer:
    df.to_excel(writer, sheet_name="TBM ESC Tower", index=False)

wb = openpyxl.load_workbook(dst_T)
ws = wb["TBM ESC Tower"]

header = [cell.value for cell in ws[1]]
admin_code_col = header.index("Admin Code") + 1
investment_id_col = header.index("Investment ID") + 1
office_col = header.index("Office") + 1
service_line_col = header.index("Service Line") + 1

for row in range(2, ws.max_row + 1):
    p_cell = f"{openpyxl.utils.get_column_letter(admin_code_col)}{row}"
    j_cell = f"{openpyxl.utils.get_column_letter(investment_id_col)}{row}"
    ws.cell(row=row, column=office_col).value = (f'=IF(ISNA(VLOOKUP({p_cell},\'OCIO ADMIN CODES\'!A:I,9,FALSE)),"",VLOOKUP({p_cell},\'OCIO ADMIN CODES\'!A:I,9,FALSE))')    
    ws.cell(row=row, column=service_line_col).value = (f'=IF(ISNA(VLOOKUP({j_cell},\'FY25 Service Lines\'!A:C,3,FALSE)),"Other - Non OCIO",VLOOKUP({j_cell},\'FY25 Service Lines\'!A:C,3,FALSE))')   

wb.save(dst_T)

In [24]:
end3 = time.time()
print(f"Elapsed time: {(end3 - start3)/60} minutes for TBM ESC files")

Elapsed time: 5.354230753580729 minutes for TBM ESC files

In [25]:
print(f"Elapsed time: {(end3 - start_master)/60} minutes for process up to now")

Elapsed time: 6.950101447105408 minutes for process up to now

## Refreshing Cloud Data ##

In [26]:
start4 = time.time()
#build TBM Tower ratios (pivot, filter for FY25)
tower_2025 = df[(df['Fiscal Year'] == 2025) & (df['Amount'] != 0)]
tower_pivot = tower_2025.pivot_table(
    index=["ESC ID", "Towers"],
    values=["Amount"],
    aggfunc="sum"
).reset_index()

tower_pivot['Ratio'] = (
    tower_pivot.groupby('ESC ID')['Amount'].transform(lambda x: x / x.sum())
)

#tower_pivot

In [27]:
#build TBM CP ratios (pivot, filter for FY25)
cp_2025 = cp_df[(cp_df['Fiscal Year'] == 2025) & (cp_df['CP Amount'] != 0)]

cp_pivot = cp_2025.pivot_table(
    index=["ESC ID", "Cost Pools"],
    values=["CP Amount"],
    aggfunc="sum"
).reset_index()

cp_pivot['Ratio'] = (
    cp_pivot.groupby('ESC ID')['CP Amount']
    .transform(lambda x: x / x.sum())
)

#cp_pivot

In [28]:
#pivot export on cloud data (actuals)
Cloud_df = pd.read_excel(raw_Cloud, sheet_name="Export", header=0)
Cloud_df = Cloud_df[Cloud_df['ESCID'].notnull()]
Cloud_len = len(Cloud_df)

In [30]:
#user to insert actual column name for billing month
Actuals = Cloud_df.pivot_table(
    index=["ESCID", "BILLING MONTH"],
    values=["COST"],
    aggfunc="sum"
).reset_index()

#Actuals

In [31]:
#create tower breakdown (join actuals and ratios)
tower_merge = Actuals.merge(tower_pivot, left_on='ESCID', right_on='ESC ID', how='left')
#ESCID = 0 + N/A mappings
tower_merge['Towers'] = tower_merge.apply(
    lambda x: 'No ESC ID Tagged' if x['ESCID'] == 0 
    else ('No CPIC Tower Projection' if pd.isna(x['Towers']) else x['Towers']), axis=1
)
#Ratio N/A mappings
tower_merge['Ratio'] = tower_merge['Ratio'].fillna(1)

tower_merge = tower_merge.drop(columns=['ESC ID','Amount'])
tower_merge['New Expenditures'] = tower_merge['COST'] * tower_merge['Ratio']
#tower_merge[tower_merge.ESCID == 3476]
#tower_merge

In [32]:
#create CP breakdown (join actuals and ratios)
cp_merge = Actuals.merge(cp_pivot, left_on='ESCID', right_on='ESC ID', how='left')
#ESCID = 0 + N/A mappings
cp_merge['Cost Pools'] = cp_merge.apply(
    lambda x: 'No ESC ID Tagged' if x['ESCID'] == 0 
    else ('No CPIC Cost Pool Projection' if pd.isna(x['Cost Pools']) else x['Cost Pools']), axis=1
)
#Ratio N/A mappings
cp_merge['Ratio'] = cp_merge['Ratio'].fillna(1)

cp_merge = cp_merge.drop(columns=['ESC ID','CP Amount'])
cp_merge['New Expenditures'] = cp_merge['COST'] * cp_merge['Ratio']
#cp_merge[cp_merge.ESCID == 2890]

In [33]:
dst_Cloud = raw_data_dst+"\ESCIDdata export_"+date_str+".xlsx"
print("Copying contents of "+raw_Cloud+" into "+dst_Cloud)
with pd.ExcelWriter(dst_Cloud, engine='openpyxl', mode='w') as writer:
    Cloud_df.to_excel(writer, sheet_name='Export', index=False)
    Actuals.to_excel(writer, sheet_name='Actuals', index=False)
    cp_pivot.to_excel(writer, sheet_name='CP Ratios', index=False)
    tower_pivot.to_excel(writer, sheet_name='Tower Ratios', index=False)
    tower_merge.to_excel(writer, sheet_name='Tower Breakdowns', index=False)
    cp_merge.to_excel(writer, sheet_name='CP Breakdown', index=False)

<>:1: SyntaxWarning: invalid escape sequence '\E'
<>:1: SyntaxWarning: invalid escape sequence '\E'
C:\Users\stephalin\AppData\Local\Temp\ipykernel_29748\446821461.py:1: SyntaxWarning: invalid escape sequence '\E'
  dst_Cloud = raw_data_dst+"\ESCIDdata export_"+date_str+".xlsx"

Copying contents of C:\Users\stephalin\Downloads\ESCID Report Oct24-Sept25.xlsx into C:\Users\stephalin\Downloads\FY25 October\Raw Data\ESCIDdata export_20251119.xlsx

In [34]:
end4 = time.time()
print(f"Elapsed time: {(end4 - start4)} seconds for Cloud data")

Elapsed time: 158.7299575805664 seconds for Cloud data

In [35]:
print("Row counts for raw data. Check with refreshed data.")
print(f"{EP_len} rows for Execution Pivot")
print(f"{Staff_len} rows for Staffing")
print(f"{CostPoolRaw_len} rows for Cost Pool")
print(f"{SolRaw_len} rows for Solution")
print(f"{TowerRaw_len} rows for Tower")
print(f"{Cloud_len} rows for Cloud Data")

Row counts for raw data. Check with refreshed data.
14993 rows for Execution Pivot
10529 rows for Staffing
18984 rows for Cost Pool
14238 rows for Solution
26103 rows for Tower
279052 rows for Cloud Data

In [36]:
folder = raw_data_dst

# List of (filename, sheetname) tuples to check
combos = [
    (dst_EP, 'Sheet1'),
    (dst_Staff, 'Import Data'),
    (dst_CostPool, 'TBM ESC Cost Pool'),
    (dst_Sol, 'TBM ESC Solutions'),
    (dst_T, 'TBM ESC Tower'),
    (dst_Cloud, 'Export')
]
print("Row counts for refreshed data. Check with raw data.")
for filename, sheetname in combos:
    path = os.path.join(folder, filename)
    df = pd.read_excel(path, sheet_name=sheetname)
    print(f'{filename} | {sheetname}: {len(df)} rows')

Row counts for refreshed data. Check with raw data.
C:\Users\stephalin\Downloads\FY25 October\Raw Data\RMS Execution Pivot Report_20251119.xlsx | Sheet1: 14993 rows
C:\Users\stephalin\Downloads\FY25 October\Raw Data\RMS Staffing Projections & Actuals_20251119.xlsx | Import Data: 10529 rows
C:\Users\stephalin\Downloads\FY25 October\Raw Data\TBM ESC Cost Pool_20251119.xlsx | TBM ESC Cost Pool: 18984 rows
C:\Users\stephalin\Downloads\FY25 October\Raw Data\TBM ESC Solutions_20251119.xlsx | TBM ESC Solutions: 14238 rows
C:\Users\stephalin\Downloads\FY25 October\Raw Data\TBM ESC Tower_20251119.xlsx | TBM ESC Tower: 26103 rows
C:\Users\stephalin\Downloads\FY25 October\Raw Data\ESCIDdata export_20251119.xlsx | Export: 279052 rows

In [37]:
input("STOP! \n 1. Check if the row counts match with the new folder. \n 2. Refresh the pivots on EP data \n 3. Run the Model Enhancements macro \n Then press Enter to continue")

STOP!
 1. Check if the row counts match with the new folder.
 2. Refresh the pivots on EP data
 3. Run the Model Enhancements macro
 Then press Enter to continue

''

## Refreshing Golden Source ##

In [38]:
start_gc = time.time()

g_src = dst_folder+"\Golden PowerBI Source File_"+date_str+".xlsx"
#g_src = dst_folder+"\Golden PowerBI Source File_"+date_str+".xlsx"

gs_df = pd.read_excel(g_src, sheet_name="Golden - Spend Tracking", header=0)
#gs_df

model = dst_folder+"\Model Enhancements_"+date_str+".xlsm"

mod_df = pd.read_excel(model, sheet_name="Combined", header=0)
#mod_df

<>:3: SyntaxWarning: invalid escape sequence '\G'
<>:9: SyntaxWarning: invalid escape sequence '\M'
<>:3: SyntaxWarning: invalid escape sequence '\G'
<>:9: SyntaxWarning: invalid escape sequence '\M'
C:\Users\stephalin\AppData\Local\Temp\ipykernel_29748\19497214.py:3: SyntaxWarning: invalid escape sequence '\G'
  g_src = dst_folder+"\Golden PowerBI Source File_"+date_str+".xlsx"
C:\Users\stephalin\AppData\Local\Temp\ipykernel_29748\19497214.py:9: SyntaxWarning: invalid escape sequence '\M'
  model = dst_folder+"\Model Enhancements_"+date_str+".xlsm"

In [39]:
serials = [
    int(float(x)) for x in mod_df['Accounting Period'].unique()
    if str(x).replace('.', '', 1).isdigit()
]
dates = pd.to_datetime(serials, unit='D', origin='1899-12-30')

today = datetime.today()
today_month = today.month
today_year = today.year

# Find serials matching today's month and year
match_idx = [
    i for i, date in enumerate(dates)
    if date.month == today_month and date.year == today_year
]

if match_idx:
    matched_serial = serials[match_idx[0]]
    filtered = mod_df[mod_df["Accounting Period"] != matched_serial]
    print("Filtered out serial:", matched_serial)
else:
    print("No matching month/year found in Accounting Period column for TBM.")

#do not filter nov/dec if it's this year because it should count for NEXT year. nov-25 is TECHNICALLY '24
#if it's nov, take data ONLY starting from oct of the year, because it counts as a new fiscal year
#REPLACE NULLS WITH ZEROS

Filtered out serial: 45985

In [40]:
#pivot combined tab in TBM Model file by Org Symbol, Oblig, Expenditure

filtered = mod_df[mod_df["Accounting Period"] != matched_serial]

filtered.columns = [
    f"New {col}" if col in ["Obligations", "Expenditures", "Ceiling"] else col
    for col in filtered.columns
]
pivot = filtered.pivot_table(
    index="Org Symbol",
    values=["New Obligations", "New Expenditures", "New Ceiling"],
    aggfunc="sum"
)

In [56]:
pivot

             New Ceiling  New Expenditures  New Obligations
Org Symbol
CEO         5.330676e+07       29382660.96     4.359248e+07
CSPO        4.837502e+07       21106056.25     4.818265e+07
DSO         2.056825e+08       83271429.96     1.722760e+08
OD          7.247933e+07       40761281.98     6.042602e+07

In [41]:
#throw them into cum oblig , cum exp on golden source file
this_year = prior_month_date.year
fy_str = f"FY{str(this_year)[-2:]}"  # "FY25"
monthtofill = (gs_df["FY"] == fy_str) & (gs_df["Month"] == month_str)

# Ensure the lengths of mask and pivot values match
mask = (gs_df["FY"] == fy_str) & (gs_df["Month"] == month_str)
rows_to_update = gs_df.loc[mask]

# Check if lengths match before assignment
if len(rows_to_update) == len(pivot):
    gs_df.loc[mask, "Cumulative Obl"] = pivot["New Obligations"].values
    gs_df.loc[mask, "Cumulative Exp"] = pivot["New Expenditures"].values
    gs_df.loc[mask, "Budget Ceiling"] = pivot["New Ceiling"].values
else:
    print("Row count mismatch: cannot assign values safely.")

gs_df[mask]

#if october, should be in N+1 year, because that's the start of the new fiscal year

,Office,Month,Month Order,CPIC,Budget Ceiling,Obligations,Expenditures,Cumulative Obl,Cumulative Exp,Obligation Projection,Org Symbol,FY
192,CUSTOMER ENGAGEMENT OFFICE,October,1,59422617,5.330676e+07,1825874.02,1066324.63,4.359248e+07,29382660.96,NaN,CEO,FY25
193,CYBERSECURITY PROGRAM OFFICE,October,1,42292711,4.837502e+07,1427192.95,866060.30,4.818265e+07,21106056.25,NaN,CSPO,FY25
194,DIGITAL SERVICES OFFICE,October,1,275116578,2.056825e+08,2329260.17,1416467.56,1.722760e+08,83271429.96,NaN,DSO,FY25
195,OFFICE OF THE DIRECTOR,October,1,57111086,7.247933e+07,1195137.54,725271.03,6.042602e+07,40761281.98,NaN,OD,FY25

In [42]:
#Calculate Obligations and Expenditures (this month's Cum Obl or Exp - last month's)
months_order = ["October", "November", "December", "January", "February", "March", "April", "May", "June","July", "August", "September"]
gs_df["Month"] = pd.Categorical(gs_df["Month"], categories=months_order, ordered=True)

prev_mask = (gs_df["FY"] == fy_str) & (gs_df["Month"] == gs_df["Month"].cat.categories[gs_df["Month"].cat.categories.get_loc(month_str)-1])

gs_df.loc[mask, "Obligations"] = gs_df.loc[mask, "Cumulative Obl"].values - gs_df.loc[prev_mask, "Cumulative Obl"].values
gs_df.loc[mask, "Expenditures"] = gs_df.loc[mask, "Cumulative Exp"].values - gs_df.loc[prev_mask, "Cumulative Exp"].values

#gs_df[mask]

In [43]:
#ensure budget ceiling #s are consistent for remainder of year

months_order = ["October", "November", "December", "January", "February", "March", "April", "May", "June","July", "August", "September"]
gs_df["Month"] = pd.Categorical(gs_df["Month"], categories=months_order, ordered=True)

source_mask = (gs_df["Month"] == month_str) & (gs_df["FY"] == fy_str)
values = gs_df.loc[source_mask, "Budget Ceiling"].values

after_mask = (gs_df["Month"] >= month_str) & (gs_df["FY"] == fy_str)
n = after_mask.sum()
gs_df.loc[after_mask, "Budget Ceiling"] = np.tile(values, int(np.ceil(n/len(values))))[:n]
gs_df[after_mask]

,Office,Month,Month Order,CPIC,Budget Ceiling,Obligations,Expenditures,Cumulative Obl,Cumulative Exp,Obligation Projection,Org Symbol,FY
192,CUSTOMER ENGAGEMENT OFFICE,October,1,59422617,5.330676e+07,NaN,NaN,4.359248e+07,29382660.96,NaN,CEO,FY25
193,CYBERSECURITY PROGRAM OFFICE,October,1,42292711,4.837502e+07,NaN,NaN,4.818265e+07,21106056.25,NaN,CSPO,FY25
194,DIGITAL SERVICES OFFICE,October,1,275116578,2.056825e+08,NaN,NaN,1.722760e+08,83271429.96,NaN,DSO,FY25
195,OFFICE OF THE DIRECTOR,October,1,57111086,7.247933e+07,NaN,NaN,6.042602e+07,40761281.98,NaN,OD,FY25
196,CUSTOMER ENGAGEMENT OFFICE,November,2,59422617,5.330676e+07,1674281.55,1497533.63,3.500156e+06,2563858.26,NaN,CEO,FY25
197,CYBERSECURITY PROGRAM OFFICE,November,2,42292711,4.837502e+07,1314281.52,1244704.70,2.741474e+06,2110765.00,NaN,CSPO,FY25
198,DIGITAL SERVICES OFFICE,November,2,275116578,2.056825e+08,2242057.98,1922268.47,4.571318e+06,3338736.03,NaN,DSO,FY25
199,OFFICE OF THE DIRECTOR,November,2,57111086,7.247933e+07,1348810.02,1131143.95,2.543948e+06,1856414.98,NaN,OD,FY25
200,CUSTOMER ENGAGEMENT OFFICE,December,3,59422617,5.330676e+07,7799470.33,1570219.28,1.129963e+07,4134077.54,NaN,CEO,FY25
201,CYBERSECURITY PROGRAM OFFICE,December,3,42292711,4.837502e+07,1464246.73,1276568.87,4.205721e+06,3387333.87,NaN,CSPO,FY25
202,DIGITAL SERVICES OFFICE,December,3,275116578,2.056825e+08,3007487.69,2229613.88,7.578806e+06,5568349.91,NaN,DSO,FY25
203,OFFICE OF THE DIRECTOR,December,3,57111086,7.247933e+07,1341515.57,1329157.14,3.885463e+06,3185572.12,NaN,OD,FY25
204,CUSTOMER ENGAGEMENT OFFICE,January,4,59422617,5.330676e+07,1893697.17,2372108.36,1.319332e+07,6506185.90,NaN,CEO,FY25
205,CYBERSECURITY PROGRAM OFFICE,January,4,42292711,4.837502e+07,4997574.83,2259039.46,9.203296e+06,5646373.33,NaN,CSPO,FY25
206,DIGITAL SERVICES OFFICE,January,4,275116578,2.056825e+08,17520304.23,3755925.09,2.509911e+07,9324275.00,NaN,DSO,FY25
207,OFFICE OF THE DIRECTOR,January,4,57111086,7.247933e+07,1285775.39,1637911.46,5.171239e+06,4823483.58,NaN,OD,FY25
208,CUSTOMER ENGAGEMENT OFFICE,February,5,59422617,5.330676e+07,1601272.82,1943562.21,1.479460e+07,8449748.11,NaN,CEO,FY25
209,CYBERSECURITY PROGRAM OFFICE,February,5,42292711,4.837502e+07,1248256.52,1800976.56,1.045155e+07,7447349.89,NaN,CSPO,FY25
210,DIGITAL SERVICES OFFICE,February,5,264651395,2.056825e+08,4653800.80,2267055.19,2.975291e+07,11591330.19,NaN,DSO,FY25
211,OFFICE OF THE DIRECTOR,February,5,57060571,7.247933e+07,2440288.43,1153900.80,7.611527e+06,5977384.38,NaN,OD,FY25
212,CUSTOMER ENGAGEMENT OFFICE,March,6,53350313,5.330676e+07,5141096.77,1470032.21,1.993569e+07,9919780.32,NaN,CEO,FY25
213,CYBERSECURITY PROGRAM OFFICE,March,6,45536505,4.837502e+07,-1073411.19,398322.11,9.378141e+06,7845672.00,NaN,CSPO,FY25
214,DIGITAL SERVICES OFFICE,March,6,215002493,2.056825e+08,3684910.11,2223815.53,3.343782e+07,13815145.72,NaN,DSO,FY25
215,OFFICE OF THE DIRECTOR,March,6,50048262,7.247933e+07,12670859.84,11886874.45,2.028239e+07,17864258.83,NaN,OD,FY25
216,CUSTOMER ENGAGEMENT OFFICE,April,7,53350313,5.330676e+07,20052358.60,2122461.07,3.998805e+07,12042241.39,NaN,CEO,FY25
217,CYBERSECURITY PROGRAM OFFICE,April,7,45536505,4.837502e+07,5082098.05,1428782.04,1.446024e+07,9274454.04,NaN,CSPO,FY25
218,DIGITAL SERVICES OFFICE,April,7,215002493,2.056825e+08,41794214.56,3911115.99,7.523204e+07,17726261.71,NaN,DSO,FY25
219,OFFICE OF THE DIRECTOR,April,7,50048262,7.247933e+07,26800436.87,1176877.85,4.708282e+07,19041136.68,NaN,OD,FY25
220,CUSTOMER ENGAGEMENT OFFICE,May,8,53350313,5.330676e+07,3140114.03,2260521.60,4.312817e+07,14302762.99,NaN,CEO,FY25
221,CYBERSECURITY PROGRAM OFFICE,May,8,45536505,4.837502e+07,12394411.88,4895248.37,2.685465e+07,14169702.41,NaN,CSPO,FY25
222,DIGITAL SERVICES OFFICE,May,8,215002493,2.056825e+08,10072635.23,33898085.32,8.530467e+07,51624347.03,NaN,DSO,FY25
223,OFFICE OF THE DIRECTOR,May,8,51740257,7.247933e+07,1721186.54,2546188.29,4.880401e+07,21587324.97,NaN,OD,FY25
224,CUSTOMER ENGAGEMENT OFFICE,June,9,53350313,5.330676e+07,2821258.18,2354118.73,4.594942e+07,16656881.72,NaN,CEO,FY25
225,CYBERSECURITY PROGRAM OFFICE,June,9,45536505,4.837502e+07,6039339.94,1421128.61,3.289399e+07,15590831.02,NaN,CSPO,FY25
226,DIGITAL SERVICES OFFICE,June,9,215002493,2.056825e+08,10887176.54,3619970.14,9.619185e+07,55244317.17,NaN,DSO,FY25
227,OFFICE OF THE DIRECTOR,June,9,51740257,7.247933e+07,4945446.47,2859444.01,5.374946e+07,24446768.98,NaN,OD,FY25
228,CUSTOMER ENGAGEMENT OFFICE,July,10,53350313,5.330676e+07,-13070756.47,6585115.88,3.287867e+07,23241997.60,NaN,CEO,FY25
229,CYBERSECURITY PROGRAM OFFICE,July,10,45536505,4.837502e+07,7173193.41,1261596.48,4.006718e+07,16852427.50,NaN,CSPO,FY25
230,DIGITAL SERVICES OFFICE,July,10,215002493,2.056825e+08,2309364.92,6655788.10,9.850121e+07,61900105.27,NaN,DSO,FY25
231,OFFICE OF THE DIRECTOR,July,10,51740257,7.247933e+07,374908.70,6041722.72,5.412437e+07,30488491.70,NaN,OD,FY25
232,CUSTOMER ENGAGEMENT OFFICE,August,11,52823532,5.330676e+07,9038957.83,2278491.66,4.191762e+07,25520489.26,4.191762e+07,CEO,FY25
233,CYBERSECURITY PROGRAM OFFICE,August,11,45536506,4.837502e+07,1252558.86,2025255.31,4.131974e+07,18877682.81,4.131974e+07,CSPO,FY25
234,DIGITAL SERVICES OFFICE,August,11,213239811,2.056825e+08,66442672.11,4716408.65,1.649439e+08,66616513.92,1.649439e+08,DSO,FY25
235,OFFICE OF THE DIRECTOR,August,11,68097774,7.247933e+07,4896518.52,1787461.95,5.902088e+07,32275953.65,5.902088e+07,OD,FY25
236,CUSTOMER ENGAGEMENT OFFICE,September,12,52823532,5.330676e+07,NaN,NaN,NaN,NaN,4.390343e+07,CEO,FY25
237,CYBERSECURITY PROGRAM OFFICE,September,12,45536506,4.837502e+07,NaN,NaN,NaN,NaN,4.813040e+07,CSPO,FY25
238,DIGITAL SERVICES OFFICE,September,12,213239811,2.056825e+08,NaN,NaN,NaN,NaN,1.738227e+08,DSO,FY25
239,OFFICE OF THE DIRECTOR,September,12,68097774,7.247933e+07,NaN,NaN,NaN,NaN,6.293546e+07,OD,FY25

In [44]:
#replace cpic proj (golden source, CPIC col), update for the month + rest of year (use esc tower data pivot: fiscal year 2025, In OCIO = True)
tower_CPIC = df_T[(df_T['In OCIO?'] == True) & (df_T['Fiscal Year'] == 2025)]
CPIC_Proj = tower_CPIC.pivot_table(
    index=["Office"],
    values=["Amount"],
    aggfunc="sum"
).reset_index()
CPIC_Proj

  Office     Amount
0    CEO   52823532
1   CSPO   45536506
2    DSO  213275758
3     OD   68097774

In [45]:
gs_df["Month"] = pd.Categorical(gs_df["Month"], categories=months_order, ordered=True)

source_mask = (gs_df["Month"] >= month_str) & (gs_df["FY"] == fy_str)
n = source_mask.sum()
repeated = np.tile(CPIC_Proj['Amount'].values, int(np.ceil(n / 4)))[:n]
gs_df.loc[source_mask, 'CPIC'] = repeated

#gs_df[source_mask]

In [46]:
GL_df = pd.read_excel(model, sheet_name="GL + Lookups", header=0)
#GL_df

In [47]:
# Fiscal quarters: 3 months each
quarters = [months_order[i:i+3] for i in range(0, 12, 3)]

#month_str = 'October'
month_idx = months_order.index(month_str)

# Find current quarter
current_qtr_idx = month_idx // 3

#Calculate Upcoming quarters (excluding current)
upcoming_quarters = len(quarters) - (current_qtr_idx + 1)
upcoming_quarters

3

In [48]:
#pivot by OCIO office, total proj oblig (only for Q4)
#For Q1-3, add UFMS commitments [QTR X] + Manual commitments [QTR X] + Other Projections [QTR X] + Payroll Proj [QTR X] + UFMS Obligations [QTR X] + UFMS Oblig
#Do this cumulatively

quarters = [
    ["UFMS Commitments Qtr 1", "Manual Commitments Qtr 1", "Other Projections Qtr 1", "Payroll Projections Qtr 1", "UFMS Obligations Qtr 1", "UFMS Obligations"],
    ["UFMS Commitments Qtr 2", "Manual Commitments Qtr 2", "Other Projections Qtr 2", "Payroll Projections Qtr 2", "UFMS Obligations Qtr 2", "UFMS Obligations"],
    ["UFMS Commitments Qtr 3", "Manual Commitments Qtr 3", "Other Projections Qtr 3", "Payroll Projections Qtr 3", "UFMS Obligations Qtr 3", "UFMS Obligations"]
]

# Cumulative sums for Qtr 1, Qtr 2, Qtr 3
for i in range(3):
    cols = [col for q in quarters[:i+1] for col in q if col in GL_df.columns]
    GL_df[f"Qtr_{i+1}"] = GL_df[cols].sum(axis=1)

# Qtr 4 is just "Total Projected Obligations"
GL_df["Qtr_4"] = GL_df["Total Projected Obligations"]

Val = [f"Qtr_{i+1}" for i in range(4)]

pivot_GL = GL_df.pivot_table(
    index="OCIO Office",
    values=Val,
    aggfunc="sum"
)

#pivot_GL

In [49]:
#delete oblig projections for clean slate
gs_df['Obligation Projection'] = np.nan

#fill in Oblig Projection based on GL Lookup pivot #s. quarter months still upcoming will be imputed
if upcoming_quarters > 0:
    quarter_months = {1: "December", 2: "March", 3: "June", 4: "September"}
    for q in range(1, upcoming_quarters + 1):
        month = quarter_months[q]
        mask = (gs_df["Month"] == month) & (gs_df["FY"] == fy_str)
        gs_df.loc[mask, "Obligation Projection"] = gs_df.loc[mask, "Org Symbol"].map(pivot_GL[f"Qtr_{q}"])
elif upcoming_quarters == 0:
    mask = (gs_df["Month"] == "September") & (gs_df["FY"] == fy_str)
    gs_df.loc[mask, "Obligation Projection"] = gs_df.loc[mask, "Org Symbol"].map(pivot_GL["Qtr_4"])


#gs_df[gs_df.Month == month_str]

In [50]:

#Cum Obl for this month is Obl Prjection
mask = (gs_df["Month"] == month_str) & (gs_df["FY"] == fy_str)
gs_df.loc[mask, "Obligation Projection"] = gs_df.loc[mask, "Cumulative Obl"]

#gs_df[after_mask]
#gs_df[gs_df.Month == month_str]

In [51]:
# Sort the DataFrame
gs_df.sort_values(by=["FY", "Office", "Month Order"], inplace=True)

# Interpolate missing values in 'Obligation Projection'
gs_df['Obligation Projection'] = gs_df.groupby(['FY', 'Office'])['Obligation Projection'].transform(lambda group: group.interpolate())
#re-sort
gs_df.sort_values(by=["FY", "Month Order","Office"], inplace=True)

#gs_df[after_mask]

In [52]:
with pd.ExcelWriter(g_src, mode='a', if_sheet_exists='replace', engine='openpyxl') as writer:
    gs_df.to_excel(writer, sheet_name='Golden - Spend Tracking', index=False)

In [ ]:
#compare cols for GL lookup tab, cloud data. make sure it matches what is fed into dashboard

In [54]:
end = time.time()

print(f"Elapsed time: {(end - start_gc)} seconds for GC refresh")

Elapsed time: 22.80122208595276 seconds for GC refresh

In [55]:
print(f"Elapsed time: {(end - start_master)/60} minutes TOTAL")

#WHEN RERUN DASHBOARD, FILTER MONTH IN GL+LOOKUPS
#projections of salary for rest of year instead of actuals through last month

Elapsed time: 23.997701597213744 minutes TOTAL